package com.pulseplayer.music.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey val id: String,
    val name: String,
    val description: String = "",
    val artworkUrl: String? = null,
    val isAutoGenerated: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
) {
    companion object {
        const val DOWNLOADED_PLAYLIST_ID = "system_downloaded"

        fun downloaded(): Playlist = Playlist(
            id = DOWNLOADED_PLAYLIST_ID,
            name = "Downloaded",
            description = "Music available offline",
            isAutoGenerated = true
        )
    }
}
